// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserRequest struct {
	// Username.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Plain text password.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// The client connection's id.
	Clientid             string   `protobuf:"bytes,3,opt,name=clientid,proto3" json:"clientid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GetUserRequest) GetClientid() string {
	if m != nil {
		return m.Clientid
	}
	return ""
}

type GetSuperuserRequest struct {
	// Username.
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSuperuserRequest) Reset()         { *m = GetSuperuserRequest{} }
func (m *GetSuperuserRequest) String() string { return proto.CompactTextString(m) }
func (*GetSuperuserRequest) ProtoMessage()    {}
func (*GetSuperuserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *GetSuperuserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSuperuserRequest.Unmarshal(m, b)
}
func (m *GetSuperuserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSuperuserRequest.Marshal(b, m, deterministic)
}
func (m *GetSuperuserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSuperuserRequest.Merge(m, src)
}
func (m *GetSuperuserRequest) XXX_Size() int {
	return xxx_messageInfo_GetSuperuserRequest.Size(m)
}
func (m *GetSuperuserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSuperuserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSuperuserRequest proto.InternalMessageInfo

func (m *GetSuperuserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CheckAclRequest struct {
	// Username.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Topic to be checked for.
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// The client connection's id.
	Clientid string `protobuf:"bytes,3,opt,name=clientid,proto3" json:"clientid,omitempty"`
	// Topic access.
	Acc                  int32    `protobuf:"varint,4,opt,name=acc,proto3" json:"acc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAclRequest) Reset()         { *m = CheckAclRequest{} }
func (m *CheckAclRequest) String() string { return proto.CompactTextString(m) }
func (*CheckAclRequest) ProtoMessage()    {}
func (*CheckAclRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *CheckAclRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAclRequest.Unmarshal(m, b)
}
func (m *CheckAclRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAclRequest.Marshal(b, m, deterministic)
}
func (m *CheckAclRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAclRequest.Merge(m, src)
}
func (m *CheckAclRequest) XXX_Size() int {
	return xxx_messageInfo_CheckAclRequest.Size(m)
}
func (m *CheckAclRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAclRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAclRequest proto.InternalMessageInfo

func (m *CheckAclRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CheckAclRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *CheckAclRequest) GetClientid() string {
	if m != nil {
		return m.Clientid
	}
	return ""
}

func (m *CheckAclRequest) GetAcc() int32 {
	if m != nil {
		return m.Acc
	}
	return 0
}

type AuthResponse struct {
	// If the user is authorized/authenticated.
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type NameResponse struct {
	// The name of the gRPC backend.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameResponse) Reset()         { *m = NameResponse{} }
func (m *NameResponse) String() string { return proto.CompactTextString(m) }
func (*NameResponse) ProtoMessage()    {}
func (*NameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *NameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameResponse.Unmarshal(m, b)
}
func (m *NameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameResponse.Marshal(b, m, deterministic)
}
func (m *NameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameResponse.Merge(m, src)
}
func (m *NameResponse) XXX_Size() int {
	return xxx_messageInfo_NameResponse.Size(m)
}
func (m *NameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NameResponse proto.InternalMessageInfo

func (m *NameResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "grpc.GetUserRequest")
	proto.RegisterType((*GetSuperuserRequest)(nil), "grpc.GetSuperuserRequest")
	proto.RegisterType((*CheckAclRequest)(nil), "grpc.CheckAclRequest")
	proto.RegisterType((*AuthResponse)(nil), "grpc.AuthResponse")
	proto.RegisterType((*NameResponse)(nil), "grpc.NameResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4f, 0x4f, 0xfa, 0x40,
	0x14, 0x84, 0x52, 0x7e, 0x3f, 0x7c, 0x21, 0xa8, 0x2b, 0x9a, 0x8a, 0x89, 0x21, 0x7b, 0xe2, 0x54,
	0xa2, 0xc6, 0xe8, 0xcd, 0xa0, 0x31, 0x78, 0xf2, 0x50, 0xe2, 0x07, 0x28, 0xcb, 0x13, 0x9a, 0x16,
	0x76, 0xd9, 0x3f, 0x1a, 0x3f, 0x99, 0x5f, 0xcf, 0x6c, 0x97, 0x92, 0x4a, 0x52, 0xc3, 0x6d, 0x67,
	0x66, 0x67, 0xdf, 0x74, 0xfa, 0x00, 0x62, 0xa3, 0x17, 0xa1, 0x90, 0x5c, 0x73, 0xe2, 0xcf, 0xa5,
	0x60, 0xbd, 0x8b, 0x39, 0xe7, 0xf3, 0x0c, 0x87, 0x39, 0x37, 0x35, 0xef, 0x43, 0x5c, 0x0a, 0xfd,
	0xe5, 0xae, 0xd0, 0x19, 0x74, 0xc6, 0xa8, 0xdf, 0x14, 0xca, 0x08, 0xd7, 0x06, 0x95, 0x26, 0x3d,
	0x68, 0x19, 0x85, 0x72, 0x15, 0x2f, 0x31, 0xa8, 0xf7, 0xeb, 0x83, 0x83, 0x68, 0x8b, 0xad, 0x26,
	0x62, 0xa5, 0x3e, 0xb9, 0x9c, 0x05, 0x9e, 0xd3, 0x0a, 0x6c, 0x35, 0x96, 0x25, 0xb8, 0xd2, 0xc9,
	0x2c, 0x68, 0x38, 0xad, 0xc0, 0xf4, 0x0a, 0x4e, 0xc6, 0xa8, 0x27, 0x46, 0xa0, 0x34, 0xfb, 0x8d,
	0xa2, 0x6b, 0x38, 0x7c, 0x5a, 0x20, 0x4b, 0x47, 0x2c, 0xdb, 0x27, 0x59, 0x17, 0x9a, 0x9a, 0x8b,
	0x84, 0x6d, 0x62, 0x39, 0xf0, 0x57, 0x26, 0x72, 0x04, 0x8d, 0x98, 0xb1, 0xc0, 0xef, 0xd7, 0x07,
	0xcd, 0xc8, 0x1e, 0xe9, 0x25, 0xb4, 0x47, 0x46, 0x2f, 0x22, 0x54, 0x82, 0xaf, 0x14, 0x92, 0x0e,
	0x78, 0x3c, 0xcd, 0x27, 0xb5, 0x22, 0x8f, 0xa7, 0x94, 0x42, 0xfb, 0x35, 0x5e, 0xe2, 0x56, 0x27,
	0xe0, 0x97, 0xb2, 0xe4, 0xe7, 0xeb, 0x6f, 0x0f, 0x8e, 0x1f, 0x25, 0x4f, 0x51, 0xda, 0xa7, 0x26,
	0x28, 0x3f, 0x12, 0x86, 0xe4, 0x16, 0xfe, 0x6f, 0x5a, 0x26, 0xdd, 0xd0, 0xfe, 0x94, 0xf0, 0x77,
	0xe9, 0x3d, 0xe2, 0xd8, 0xf2, 0x78, 0x5a, 0x23, 0x0f, 0xd0, 0x2e, 0xd7, 0x46, 0xce, 0xb7, 0xde,
	0xdd, 0x2a, 0x2b, 0x1e, 0xb8, 0x83, 0x56, 0x51, 0x22, 0x39, 0x75, 0x37, 0x76, 0x4a, 0xad, 0x34,
	0xda, 0xc0, 0xf6, 0x6b, 0xc9, 0x59, 0xe8, 0xf6, 0x27, 0x2c, 0xf6, 0x27, 0x7c, 0xb6, 0xfb, 0x53,
	0x18, 0xcb, 0x8d, 0xd0, 0x1a, 0xb9, 0x07, 0xff, 0x25, 0xce, 0x74, 0xa5, 0xab, 0x82, 0xa7, 0xb5,
	0xe9, 0xbf, 0x9c, 0xb9, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0x28, 0x8b, 0x06, 0xfc, 0xc1, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BrokerAuthServiceClient is the client API for BrokerAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrokerAuthServiceClient interface {
	// GetUser tries to authenticate a user.
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// GetSuperuser checks if a user is a superuser.
	GetSuperuser(ctx context.Context, in *GetSuperuserRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// CheckAcl checks user's authorization for the given topic.
	CheckAcl(ctx context.Context, in *CheckAclRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// GetName retrieves the name of the backend.
	GetName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NameResponse, error)
	// Halt signals the backend to halt.
	Halt(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type brokerAuthServiceClient struct {
	cc *grpc.ClientConn
}

func NewBrokerAuthServiceClient(cc *grpc.ClientConn) BrokerAuthServiceClient {
	return &brokerAuthServiceClient{cc}
}

func (c *brokerAuthServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/grpc.BrokerAuthService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerAuthServiceClient) GetSuperuser(ctx context.Context, in *GetSuperuserRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/grpc.BrokerAuthService/GetSuperuser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerAuthServiceClient) CheckAcl(ctx context.Context, in *CheckAclRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/grpc.BrokerAuthService/CheckAcl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerAuthServiceClient) GetName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NameResponse, error) {
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, "/grpc.BrokerAuthService/GetName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerAuthServiceClient) Halt(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/grpc.BrokerAuthService/Halt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerAuthServiceServer is the server API for BrokerAuthService service.
type BrokerAuthServiceServer interface {
	// GetUser tries to authenticate a user.
	GetUser(context.Context, *GetUserRequest) (*AuthResponse, error)
	// GetSuperuser checks if a user is a superuser.
	GetSuperuser(context.Context, *GetSuperuserRequest) (*AuthResponse, error)
	// CheckAcl checks user's authorization for the given topic.
	CheckAcl(context.Context, *CheckAclRequest) (*AuthResponse, error)
	// GetName retrieves the name of the backend.
	GetName(context.Context, *emptypb.Empty) (*NameResponse, error)
	// Halt signals the backend to halt.
	Halt(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

// UnimplementedBrokerAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBrokerAuthServiceServer struct {
}

func (*UnimplementedBrokerAuthServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedBrokerAuthServiceServer) GetSuperuser(ctx context.Context, req *GetSuperuserRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuperuser not implemented")
}
func (*UnimplementedBrokerAuthServiceServer) CheckAcl(ctx context.Context, req *CheckAclRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAcl not implemented")
}
func (*UnimplementedBrokerAuthServiceServer) GetName(ctx context.Context, req *emptypb.Empty) (*NameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetName not implemented")
}
func (*UnimplementedBrokerAuthServiceServer) Halt(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Halt not implemented")
}

func RegisterBrokerAuthServiceServer(s *grpc.Server, srv BrokerAuthServiceServer) {
	s.RegisterService(&_BrokerAuthService_serviceDesc, srv)
}

func _BrokerAuthService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerAuthServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BrokerAuthService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerAuthServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerAuthService_GetSuperuser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuperuserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerAuthServiceServer).GetSuperuser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BrokerAuthService/GetSuperuser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerAuthServiceServer).GetSuperuser(ctx, req.(*GetSuperuserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerAuthService_CheckAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerAuthServiceServer).CheckAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BrokerAuthService/CheckAcl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerAuthServiceServer).CheckAcl(ctx, req.(*CheckAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerAuthService_GetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerAuthServiceServer).GetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BrokerAuthService/GetName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerAuthServiceServer).GetName(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerAuthService_Halt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerAuthServiceServer).Halt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BrokerAuthService/Halt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerAuthServiceServer).Halt(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _BrokerAuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.BrokerAuthService",
	HandlerType: (*BrokerAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _BrokerAuthService_GetUser_Handler,
		},
		{
			MethodName: "GetSuperuser",
			Handler:    _BrokerAuthService_GetSuperuser_Handler,
		},
		{
			MethodName: "CheckAcl",
			Handler:    _BrokerAuthService_CheckAcl_Handler,
		},
		{
			MethodName: "GetName",
			Handler:    _BrokerAuthService_GetName_Handler,
		},
		{
			MethodName: "Halt",
			Handler:    _BrokerAuthService_Halt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
